### ISSUE TITLE
New Discord update broke the script

### ISSUE THREAD

**Issue by xd-mau5** [An00nymushun/DiscordFreeStickers#26]
**Describe the bug**
New Discord update broke the script

**To Reproduce**
`Update discord`

Update discord

`Make sure you can reproduce this problem yourself with your steps after restarting Discord!`

**Expected behavior**
Script starting and working
**Screenshots**
![image](https://user-images.githubusercontent.com/73971855/192575898-33ea9f12-54c1-4705-aaf1-cf3d1d407f6c.png)

**Client:**
 - Desktop [Windows 10 64-Bit (10.0.19044)]
 - Discord Build Channel [Stable 149345 (f0be125)]
 - Plugin Version [1.3.2]
 - BD Version (1.7.0)

**Comment by Enferlain** [comment]
Yeah says this for me

![image](https://user-images.githubusercontent.com/15861396/192787291-474b6445-247f-4c0e-89af-cdfa0b4137bc.png)

**Comment by Jdbye** [comment]
A lot of other plugins seem to be broken as well including DiscordFreeEmojis.

**Comment by xd-mau5** [comment]
> A lot of other plugins seem to be broken as well including DiscordFreeEmojis.

That one is working well, maybe you have a old version

**Comment by Jdbye** [comment]
> > A lot of other plugins seem to be broken as well including DiscordFreeEmojis.
> 
> That one is working well, maybe you have a old version

I used the one from BetterDiscord's plugin database, maybe it's outdated.

**Comment by Squishyzbear** [comment]
.

**Comment by AdityaDragonBeast** [comment]
Facing the same is
![image](https://user-images.githubusercontent.com/99749097/193215744-534ef688-2b0d-4f24-a4cf-863bf2d22096.png)
sue

**Comment by command-music** [comment]
It also happened on my Mac!

iMac 24" (2021)
OS X 10.15.7 (22.1.0)
macOS Ventura 13.0 Beta (22A5352e)
Discord PTB 150586 (dd1a31e)
Host 0.0.64

**Comment by Ashesh3** [comment]
+1 Plugin seems broken as of now. @An00nymushun any updates on this?

**Comment by aqtsalt** [comment]
update?

**Comment by An00nymushun** [comment]
It should work now

**Comment by EEize** [comment]
> 

Still doesnt work
*nvm works fine now

**Comment by Ashesh3** [comment]
Works great here! Thanks for the update.

**Comment by Enferlain** [comment]
Yea it works, thanks

**Comment by LavenderAndChamomile** [comment]
Still doesn't work for me

**- Stable 156406 (28abb43) 
- Host 1.0.9007 
- Windows 10 64-Bit (10.0.19045)
- Core V1.8.2**

**Comment by theBonkster** [comment]
> It should work now

it not working

**Comment by EEize** [comment]
Did you download it properly?

**Comment by LavenderAndChamomile** [comment]
It worked once in a Discord server, then stopped when I tried it in a DM.

**Comment by theBonkster** [comment]
> Did you download it properly?

i think so

**Comment by noob111111** [comment]
![image](https://user-images.githubusercontent.com/90646226/204116292-759063ab-b390-47b1-a619-f9e15cd87bba.png)

META was not found.

I am pretty sure I downloaded it correctly

**Comment by EEize** [comment]
Tutorial how to download it properly:
1. Click on ["FreeStickers.plugin.js"](https://github.com/An00nymushun/DiscordFreeStickers/blob/main/FreeStickers.plugin.js)
2. Then tap ["Raw"](https://raw.githubusercontent.com/An00nymushun/DiscordFreeStickers/main/FreeStickers.plugin.js)
3. After that on this page press right mouse button and select "Save as..."
4. Put downloaded file into BetterDiscord's plugin folder(Don't forget to remove "(1)" at the end of the file if you have one)

**Comment by Jps838898** [comment]
> lugin seems broken as of now. @An00nymushun any updates on th

Thanks for this wprks now

**Comment by LavenderAndChamomile** [comment]
> Tutorial how to download it properly:
> 
> 1. Click on ["FreeStickers.plugin.js"](https://github.com/An00nymushun/DiscordFreeStickers/blob/main/FreeStickers.plugin.js)
> 2. Then tap ["Raw"](https://raw.githubusercontent.com/An00nymushun/DiscordFreeStickers/main/FreeStickers.plugin.js)
> 3. After that on this page press right mouse button and select "Save as..."
> 4. Put downloaded file into BetterDiscord's plugin folder(Don't forget to remove "(1)" at the end of the file if you have one)

Still doesn't work for me :(

**Comment by LavenderAndChamomile** [comment]
> Tutorial how to download it properly:
> 
> 1. Click on ["FreeStickers.plugin.js"](https://github.com/An00nymushun/DiscordFreeStickers/blob/main/FreeStickers.plugin.js)
> 2. Then tap ["Raw"](https://raw.githubusercontent.com/An00nymushun/DiscordFreeStickers/main/FreeStickers.plugin.js)
> 3. After that on this page press right mouse button and select "Save as..."
> 4. Put downloaded file into BetterDiscord's plugin folder(Don't forget to remove "(1)" at the end of the file if you have one)

Works fine now! 😄

**Comment by SoV3n04ek** [comment]
> It should work now

Do u have some success?

**Comment by LavenderAndChamomile** [comment]
works fine now :)
